name: "manual build"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: release extension
        run: npm run release
      - name: production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: chinese-programmer-wrong-pronunciation-chromium-extension
          retention-days: 7
          path: dist/chinese-programmer-wrong-pronunciation-chromium-extension.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/chinese-programmer-wrong-pronunciation-chromium-extension.zip
